"""
Parameter file for api
"""
from sklearn.preprocessing import MinMaxScaler


class PredictParams: 
     """
    class containing every parameter
    """    def __init__(self): 
         self.topfeat = ['AMT_ANNUITY', 'AMT_CREDIT', 'AMT_INCOME_TOTAL', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR', 'ANNUITY_INCOME_PERC', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'COMMONAREA_MEDI', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'HOUR_APPR_PROCESS_START', 'INCOME_CREDIT_PERC', 'INCOME_PER_PERSON', 'LANDAREA_AVG', 'LIVINGAREA_MODE', 'NONLIVINGAREA_AVG', 'OBS_30_CNT_SOCIAL_CIRCLE', 'OWN_CAR_AGE', 'PAYMENT_RATE', 'REGION_POPULATION_RELATIVE', 'TOTALAREA_MODE', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BEGINEXPLUATATION_MODE']    